const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const indexHtml = fs.readFileSync(path.join(root, 'app', 'index.html'), 'utf8');
const setupHtml = fs.readFileSync(path.join(root, 'app', 'setup.html'), 'utf8');
const game = fs.readFileSync(path.join(root, 'app', 'game.js'), 'utf8');
const server = fs.readFileSync(path.join(root, 'app', 'server.py'), 'utf8');
const configRoute = fs.readFileSync(path.join(root, 'app', 'server_routes', 'config.py'), 'utf8');
const configRuntime = fs.readFileSync(path.join(root, 'app', 'server_services', 'config_runtime.py'), 'utf8');
const weatherProviders = fs.readFileSync(path.join(root, 'app', 'services', 'weather_providers.py'), 'utf8');
const weatherSettings = fs.readFileSync(path.join(root, 'app', 'weather-settings.js'), 'utf8');
const weatherLocalization = fs.readFileSync(path.join(root, 'app', 'weather-localization.js'), 'utf8');
const style = fs.readFileSync(path.join(root, 'app', 'style.css'), 'utf8');
const en = JSON.parse(fs.readFileSync(path.join(root, 'app', 'locales', 'en.json'), 'utf8'));
const zh = JSON.parse(fs.readFileSync(path.join(root, 'app', 'locales', 'zh.json'), 'utf8'));

assert.ok(indexHtml.includes('onclick="mmTestWeather()"'), 'main settings should expose a weather test button');
assert.ok(indexHtml.includes('id="mm-weather-status"'), 'main settings should have a weather test status container');
assert.ok(indexHtml.includes('class="mm-weather-row"'), 'main settings weather controls should use a stable grid row');
assert.ok(indexHtml.includes('class="mm-weather-actions"'), 'main settings weather test button should be on its own row');
assert.ok(/style\.css\?v=[^"]*weather-form-layout/.test(indexHtml), 'main settings should bust cached weather form CSS');
assert.ok(indexHtml.includes('data-i18n-placeholder="weather_city_placeholder"'), 'main settings city input should have a specific placeholder');
assert.ok(indexHtml.includes('data-i18n-placeholder="weather_region_placeholder"'), 'main settings region input should be clearly optional');
assert.ok(indexHtml.includes('id="mm-weather-provider"'), 'main settings should expose a weather provider selector');
assert.ok(indexHtml.includes('id="mm-qweather-api-host"'), 'main settings should expose the dedicated QWeather API Host');
assert.ok(indexHtml.includes('id="mm-qweather-api-key"'), 'main settings should expose a masked QWeather API Key input');
assert.ok(indexHtml.includes('id="mm-weather-longitude"') && indexHtml.includes('id="mm-weather-latitude"'), 'main settings should collect precise coordinates');
assert.ok(indexHtml.includes('id="mm-weather-locate"') && indexHtml.includes('VOWeatherSettings.locateCurrentPosition()'), 'main settings should offer browser geolocation');
assert.ok(weatherSettings.includes('navigator || {}).geolocation') && weatherSettings.includes('enableHighAccuracy: true'), 'weather settings should request high-accuracy browser coordinates');
assert.ok(indexHtml.includes('weather-settings.js?v='), 'main settings should load the focused weather settings module');
assert.ok(indexHtml.indexOf('weather-localization.js') < indexHtml.indexOf('game.js'), 'weather localization must load before the weather renderer');
assert.ok(style.includes('.mm-weather-row') && style.includes('grid-template-columns: minmax(0, 1fr) 82px'), 'main settings weather row should preserve input widths');
assert.ok(style.includes('.mm-weather-actions'), 'main settings weather action row should be styled');
assert.ok(setupHtml.includes('onclick="testSetupWeather()"'), 'setup wizard should expose a weather test button');
assert.ok(setupHtml.includes('id="s-weather-status"'), 'setup wizard should have a weather test status container');
assert.ok(setupHtml.includes('class="weather-row"'), 'setup wizard weather controls should use a stable grid row');
assert.ok(setupHtml.includes('data-i18n-placeholder="weather_city_placeholder"'), 'setup city input should have a specific placeholder');
assert.ok(setupHtml.includes('data-i18n-placeholder="weather_region_placeholder"'), 'setup region input should be clearly optional');

assert.ok(game.includes('function mmTestWeather()'), 'main settings should implement weather test handler');
assert.ok(game.includes('VOWeatherSettings.requestTest(weatherConfig'), 'main settings weather test should use the secret-safe POST helper');
assert.ok(weatherSettings.includes("request('/api/weather/test'"), 'weather settings helper should POST weather tests');
assert.ok(game.includes('var _voWeatherLocation =') && game.includes('function _refreshWeatherLocationFromConfig()'), 'floor window tooltip should read weather location from server config');
assert.ok(game.includes('function _applyWeatherTestResult(location, result)'), 'weather test should have an in-page apply helper');
assert.ok(game.includes('officeConfig.weather.location = location || result.location'), 'weather test should update current office weather location');
assert.ok(game.includes('current.description || result.weather ||'), 'weather test should update current weather description');
assert.ok(game.includes('weatherData.updatedAt = parseInt(result.updatedAt, 10) || Date.now();'), 'weather test should store weather update time');
assert.ok(game.includes('weatherData.humidity = Number.isFinite(Number(current.humidity))'), 'weather test should immediately update humidity');
assert.ok(weatherLocalization.includes('smoky\\s+haze') && weatherLocalization.includes("'烟霾'"), 'weather localization should cover common English haze descriptions');
assert.ok(game.includes("Date.parse(data.observedAt || '')"), 'weather polling should prefer the provider observation time');
assert.ok(game.includes('_applyWeatherTestResult(weatherConfig.location, d);'), 'successful main-menu weather test should immediately update hover data');
assert.ok(setupHtml.includes('function testSetupWeather()'), 'setup wizard should implement weather test handler');
assert.ok(setupHtml.includes("fetch('/api/weather/test?location=' + encodeURIComponent(location))"), 'setup wizard weather test should call weather test API');

assert.ok(server.includes('request_path in {"/weather-proxy", "/api/weather/test"}'), 'server should delegate weather GET routes');
assert.ok(configRoute.includes('path == "/api/weather/test"'), 'config route should expose weather test endpoint');
assert.ok(configRuntime.includes('DEFAULT_WEATHER_SERVICE.current'), 'weather route should use the provider-neutral weather service');
assert.ok(weatherProviders.includes('/v7/weather/now?'), 'weather provider layer should call QWeather current conditions');
assert.ok(weatherProviders.includes('wttr.in/{encoded}?format=j1'), 'weather provider layer should retain the compatibility fallback');
assert.ok(configRuntime.includes('"resolvedLocation"'), 'weather test endpoint should return resolved location');
assert.ok(configRuntime.includes('"tempF"') && configRuntime.includes('"tempC"'), 'weather test endpoint should return temperatures');
assert.ok(configRuntime.includes('"updatedAt": data.get("fetchedAt") or int(time.time() * 1000)'), 'weather test endpoint should return provider fetch time with a collection-time fallback');

assert.strictEqual(en.test_weather, '🔍 Test');
assert.strictEqual(zh.test_weather, '🔍 检测');
assert.strictEqual(zh.weather_city_placeholder, '城市，例如 Beijing');
assert.strictEqual(zh.weather_region_placeholder, '地区，可选');
assert.strictEqual(zh.weather_test_ok, '天气位置可用');
assert.strictEqual(zh.weather_test_location_required, '请先输入天气位置');
assert.strictEqual(en.weather_updated_at, 'Updated at');
assert.strictEqual(zh.weather_updated_at, '更新时间');
assert.strictEqual(en.humidity, 'Humidity');
assert.strictEqual(zh.humidity, '湿度');

console.log('weather location test UI checks passed');
