"""Managed launcher scripts for VO-registered stdio MCP servers."""

from __future__ import annotations

import os
import shlex
import shutil
from pathlib import Path
from typing import Any


def launcher_path(status_dir: str, name: str) -> Path:
    return Path(status_dir) / "mcp" / name / "run-mcp.sh"


def stdio_command_error(server: dict[str, Any]) -> str:
    if server.get("transport") != "stdio":
        return ""
    command = str(server.get("command") or "").strip()
    if not command:
        return "MCP command is empty"
    if os.path.isabs(command):
        return "" if os.path.exists(command) else f"MCP command not found: {command}"
    if "/" in command:
        cwd = str(server.get("cwd") or "").strip()
        candidate = Path(cwd or ".") / command
        return "" if candidate.exists() else f"MCP command not found: {candidate}"
    return "" if shutil.which(command) else f"MCP command not found in PATH: {command}"


def ensure_stdio_launcher(status_dir: str, server: dict[str, Any]) -> str:
    """Create a stable VO-managed launcher for stdio servers and return its path."""
    if server.get("transport") != "stdio":
        return ""
    name = str(server.get("name") or "").strip()
    command = str(server.get("command") or "").strip()
    if not name or not command:
        return ""

    path = launcher_path(status_dir, name)
    path.parent.mkdir(parents=True, exist_ok=True)
    args = [str(item) for item in server.get("args") or []]
    env = server.get("env") if isinstance(server.get("env"), dict) else {}
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by Virtual Office MCP registry.",
        "# Edit the MCP registry entry in VO instead of editing this file.",
    ]
    cwd = str(server.get("cwd") or "").strip()
    if cwd:
        lines.append(f"cd {shlex.quote(cwd)}")
    for key in sorted(env):
        lines.append(f"export {key}={shlex.quote(str(env[key]))}")
    launch = " ".join(shlex.quote(part) for part in [command, *args])
    lines.append(f"exec {launch} \"$@\"")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    path.chmod(0o755)
    return str(path)


def client_config_server(status_dir: str, server: dict[str, Any]) -> dict[str, Any]:
    """Return the stdio server shape clients should store: one managed launcher."""
    if server.get("transport") != "stdio":
        return dict(server)
    launcher = ensure_stdio_launcher(status_dir, server)
    client_server = dict(server)
    if launcher:
        client_server["command"] = launcher
        client_server.pop("args", None)
        client_server.pop("cwd", None)
        client_server.pop("env", None)
        client_server["launcherPath"] = launcher
    return client_server
